### ISSUE TITLE
TariffPeakOnWeekends definition still incorrect in latest default config

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#10]
As per title

**Comment by BJReplay** [comment]
Build 1.4.3.1 Release Notes

** IMPORTANT - BAD SAMPLE CONFIG ENTRIES **

A number of config entries were listed incorrectly as shown immediately below - with a Type Attribute and Scope Attribute and a Profile Attribute
These are incorrect.

    <Setting Name="DebugLogging" Type="System.Boolean" Scope="Application">
      <Value Profile="(Default)">False</Value>
    </Setting>    


The correct form for these is as shown below.
For information about each setting, refer to the original release notes below.

    <Setting Name="DebugLogging" serializeAs="String">
      <Value>False</Value>
    </Setting>            
    <setting name="PWControlEnabled" serializeAs="String">
      <value>True</value>
    </setting>
    <Setting Name="PWOvernightStandby" serializeAs="String">
      <Value>False</Value>
    </Setting>
    <Setting Name="PWWeekendStandbyTarget" serializeAs="String">
      <Value>5</Value>
    </Setting>
    <Setting Name="PWWeekendStandbyOnTarget" serializeAs="String">
      <Value>False</Value>
    </Setting>
