### ISSUE TITLE
When in charge mode, decreased forecast PV doesn't increase charge target.

### ISSUE THREAD

**Issue by BJReplay** [BJReplay/PowerwallService#15]

**Comment by spoonwzd** [comment]
Might be worth checking the inverse behavior too, so that increased forecast PV switches to self consumption for discharge?

Would need to set a threshold for these too so it's not too sensitive.

**Comment by spoonwzd** [comment]
Is v1.4.2.1 good for use?

**Comment by BJReplay** [comment]
Yes.  Currently affected by #13, #14, and #15, all minor.  I've checked in
the code for 1.4.3.1 which fixes those three issues but haven't uploaded a
build - last night proved 13 and 14, haven't yet had a chance to prove 15
(it requires the forecast to drop overnight), so fee free to build.

**Comment by spoonwzd** [comment]
Yup seems fine. Is it likely to charge during off-peak now if SoC is below target when a later prediction sets a higher target?
