### ISSUE TITLE
Mutli-PV System Support

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#18]
As it is not possible to accurately forecast PV systems that are built from multiple arrays, my estimates are unreliable and hugely affect the effectiveness of @BJReplay's otherwise awesome utility.

It would be great if PwS was able to cater for this configuration by adding the estimates of both systems together while ensuring the estimate never exceeds a specific limit at each estimation interval in the JSON feed. Hopefully this is simple enough to add.

In terms of configuration variables, I perceive something like:

Currently:
PVSystemLongitude
PVSystemLattitude
PVSystemCapacity
PVSystemTilt
PVSystemAzimuth
PVSystemInstallDate

Proposed:
PVSystem1Longitude
PVSystem1Lattitude
PVSystem1Capacity
PVSystem1Tilt
PVSystem1Azimuth
PVSystem1InstallDate
PVSystem2Longitude
PVSystem2Lattitude
PVSystem2Capacity
PVSystem2Tilt
PVSystem2Azimuth
PVSystem2InstallDate
PVSystemCap

PVSystem1 results + PVSystem2 results (ensuring PVSystemCap is not exceeded at any Solcast output interval when results are added together) = Accurate PV reporting!

**Comment by spoonwzd** [comment]
What help do you need @BJReplay ?

**Comment by BJReplay** [comment]
Another developer to take on this enhancement, @spoonwzd

**Comment by spoonwzd** [comment]
Really? Why? The code already exists, so isn't it just a case of duplicating it with altered variable names and then a simple mathematical function to combine the results before the rest of the code carries on as per usual?

I'm not a coder, but I understand the principles and logic. This doesn't seem difficult to me.

If it's incentive you need, I would be willing to financially contribute a donation towards development efforts!

**Comment by spoonwzd** [comment]
Thanks @livenoise - these changes are working great!

**Comment by BJReplay** [comment]
Thanks @livenoise
