### ISSUE TITLE
Issues with firmware v1.17.1

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#25]
I had 1.71.1 pushed out to my Powerwall at some point yesterday. It seems the new firmware is causing issues with PwS for me.

Most of the time when I start the service, I see the following errors in the event logs:

```
The remote server returned an error: (401) Unauthorized.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)

The remote server returned an error: (403) Forbidden.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetPWSecureAPIResult[JSONType](String API, Boolean ForceReLogin)

The remote server returned an error: (401) Unauthorized.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)

Failed to obtain current operation mode
```

There were also similar 401/403 issues reported overnight when exiting charge mode and changing target levels.

Sometimes the function _does_ work, but I'm not exaggerating when I say it's 10% of the time.

Any ideas?

**Comment by BJReplay** [comment]
No, that is a concern.

I have been stuck on 1.15.3 for quite some time.

I have also seen reports on TMC of other issues with 1.17.1 - https://teslamotorsclub.com/tmc/threads/1-17-1.115580/ so perhaps there are some bugs in the gateway web interface in this issue.

I have used postman (https://www.getpostman.com) to help understand the API, and most of the discovered API commands are documented at https://github.com/vloschiavo/powerwall2, but really all I can suggest is trying the login command in postman which is a post to /api/login/Basic with a body of {"username":"whatever@whatever.co.uk", "password":"ST17XXXXXXXX", "force_sm_off":false}

This might allow you to see a little more of the response to find out if there is any other information returned when you can't log in.

What is really odd is that it does work sometimes!

**Comment by spoonwzd** [comment]
I'll have a play with the API later and see if I can work out what's going on.

Looking at what happened last night, I think I'm going to have to stop PwS completely for now, as it doesn't seem to retry a command after failing to execute and therefore isn't forcing itself past the issue. :(

Also, after setting PWControlEnabled to 'False' PwS still seems to authenticate with the Powerwall to get the current operation mode - is this right?

**Comment by BJReplay** [comment]
Yes it does - ideally it shouldn't.  I'll fix that on the version I'm working on at the moment, but the new version is a complete re-write, so is a while away.

**Comment by spoonwzd** [comment]
Ok cool - I was just using that as a measure to see if PWControlEnabled being False was working, so thanks for confirming.

In regards to v2, does that mean you won't be spending any time on the current code if I work out what's going on with the v1.17.1 API? My gut feel is that it's just a timing issue.

**Comment by spoonwzd** [comment]
Looks like there aren't any PV generation estimates with PWControlEnabled set to disabled either - I thought this was supposed to still happen?

**Comment by spoonwzd** [comment]
Using curl to poke the Powerwall I'm unable to get the auth token:

```
curl -s -i -X POST -H "Content-Tyd":"ST17K000XXXX,"force_sm_off":false}' http://192.168.xxx.xxx/api/login/Basic

HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept, Accept-Encoding, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Content-Type: application/json
X-Content-Type-Options: nosniff
Date: Sun, 03 Jun 2018 08:03:31 GMT
Content-Length: 66

{"code":401,"error":"Cannot Start Wizard","message":"Login Error"}
```

Taking a closer look at the Gateway's web interface, it looks like they've added a new check to the wizard. When I try and run the wizard and enter the credentials a new section pops up stating that I [must click a check box to get any further](https://gate.spoonwizard.com/images/pw20180603.jpg) while the Powerwall is in operation.

I did a packet capture to see what was going on. Looks like it's as simple as setting "force_sm_off":true to resolve the issue.

```
curl -s -i -X POST -H "Content-Type: application/json" -d '{"username":"dave@internet.com","password":"ST17K000XXXX","force_sm_off":true}' 

http://192.168.xxx.xxx/api/login/Basic
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept, Accept-Encoding, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Set-Cookie: AuthCookie=JXzpxZ_2G1GD_joFtlVYu3DvaDx5z-XdNNDO-IzizfJ0uXXkfHgkCIBtQpW2XUAYou6ALWfEyuJ_ej_trLJDpQ==; Path=/
Date: Sun, 03 Jun 2018 08:25:08 GMT
Content-Length: 202
Content-Type: text/plain; charset=utf-8

{"email":null,"firstname":"Tesla","lastname":"Energy","roles":["Provider_Engineer"],"token":"JXzpxZ_2G1GD_joFtlVYu3DvaDx5z-XdNNDO-IzizfJ0uXXkfHgkCIBtQpW2XUAYou6ALWfEyuJ_ej_trLJDpQ==","provider":"Basic"}
```

Are you able to update the current build and issue a new executable? I can probably get @livenoise to do this tomorrow for me at work if you can't and I'm lucky :)

**Comment by BJReplay** [comment]
[PowerwallService.zip](https://github.com/BJReplay/PowerwallService/files/2065838/PowerwallService.zip)
I could have probably hex-edited the EXE, but did a new build.  Thanks for diagnosing.  The fix was easy as force_sm_off was already being passed as a parameter and set to false.

**Comment by spoonwzd** [comment]
Nice one. I'll try it now.

Does the build include the 2nd PV array changes from @livenoise ?

**Comment by BJReplay** [comment]
Arrrgh - no.  I based my new version off his fix.

**Comment by BJReplay** [comment]
Let me see if I can quickly swap branches - no guarantees though.  It is a one line change for @livenoise - line 853 gets changed to .force_sm_off = True

**Comment by spoonwzd** [comment]
Looks like it is? Generation stats look ok.

Successfully got current mode!

`Current PW Mode=autonomous, BackupPercentage=5, APIResult = 202`

**Comment by BJReplay** [comment]
It turns out I'd already accepted the pull request into master, so yes, it is.

**Comment by spoonwzd** [comment]
All good then. :) Thanks!

**Comment by BJReplay** [comment]
Re No PV generation estimates with PWControlEnabled = false, yes, that's a change in the other branch - won't be putting that in master any time soon, sorry.

**Comment by spoonwzd** [comment]
No biggie - only wanted it as I use those stats in a meter from the 1000 event log PwS generates. All working now anyway, so back to normal 👍

**Comment by BJReplay** [comment]
By the way, that check box shouldn't be needed, because you (presumably) weren't off grid and you weren't in the middle of a firmware update.  I'm guessing that the update to 1.17.1 has left the system thinking it is in the middle of a firmware update.

**Comment by spoonwzd** [comment]
That's how I read it too at first, but I think you also need it if the Powerwall is in operation. I can only conclude that the times that it did work overnight were those times when it was not in operation - ie. empty and not charging.

**Comment by spoonwzd** [comment]
"If you want to launch the Wizard _and stop system operation_, select Force Launch Wizard."

**Comment by BJReplay** [comment]
Interestingly 1.17.2 has dropped for some people.  Might indicate the other issues 1.17.1 have required a fairly quick release.  Users are reporting that their fan isn't working with 1.17.2 though.

The "click for more" option on login is there on 1.15.3 - it's been there for a while.

I think that whatever the login checks for before allowing login is failing on 1.17.1, but wasn't before - that's why you've never needed to set the force check box to true up until 1.17.1.

**Comment by spoonwzd** [comment]
I was 1.15.1 for ages before moving to 1.17.1 - I never had 1.15.3 so the force login was new to me.

Fan failures don't sound great - I've heard it limits charge rates on units with failed fans as it can't manage the heat :(

**Comment by spoonwzd** [comment]
I wish Tesla would publish their changelog like they do for the car updates
