### ISSUE TITLE
PW URL is now HTTPS - PWS 1.0.1 breaks

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#26]
My PW firmware updated overnight from 1.15.1 to 1.19.0 and both PWS and PVOutput Integration service broke as a result.

I've read elsewhere that from 1.18.x the PW uses HTTPS now using a self-signed cert.

I was able to get the PVOutput integration service working again by simply changing the URLs that point to the PW internal webserver in their conf file from HTTP to HTTPS.

For PWS this has not worked. I'm guessing something possibly needs to be changed in the code to handle the HTTPS URL in these newer firmware revisions?

**Comment by BJReplay** [comment]
Just got home after a week away.  Will crack out the tools and have a look over the weekend.  I'm still stuck on 1.15.3 (luckily).  I won't be able to test any fix (unless you want to set up a VPN for me to debug over) until I am on 1.19.0

**Comment by AnthonyBe** [comment]
No problem. I'm happy to test any new compiled binaries. Because I'm only using PWS in logging/monitoring mode, there's no impact of it doesn't work. And I'm guessing it is pretty binary; it either will or won't work!

**Comment by BJReplay** [comment]
OK, the quickest work around appears to be to add the certificate to the Trusted Root Certification Authorities - either for the Local Computer (should work if PWS is running under Network Service) or the store for the service account.  If you can try that in the first instance and let me know, that would be great.

Alternatives are to ignore the certificate (set up a validation callback to validate the certificate that always returns true) - but to do that I need to refactor so that I have methods that ignore certificates if they're talking to a Powerwall, but don't ignore them if they are talking to PVOutput, for example, or be happy to ignore all certificates (not a good idea), or to explicitly handle that certificate - but that would require setup that is at least as complex as just adding the cert to the trusted root certificate authorities on the machine (e.g. adding the certificates hash to the config so the validator could accept it).

If you can get past this by adding the cert to the trusted root cert authorities store, I'll add that to the setup instructions.

P.S. I assume you already updated the PWS config to point to the https gateway address :)

**Comment by AnthonyBe** [comment]
I downloaded the cert and installed it into the Local Computer store, started PSW, but got the same error unfortunately:

```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)
```

..and yes, I had already updated the PWGatewayAddress URL to HTTPS in the PowerwallService.exe.config :)

> need to refactor so that I have methods that ignore certificates if they're talking to a Powerwall, but don't ignore them if they are talking to PVOutput

this seems to be the best approach in my mind as it removes a lot of complication as people move to the newer firmware on their PW, but keeps communications to PVOutput (and PowerBI and Solcast) secure.

**Comment by BJReplay** [comment]
Thanks for the error details. I will progress the change to ignore
certificates.

**Comment by AnthonyBe** [comment]
So you have full information, 4 errors thrown by PWS when started:

```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)
```
and

```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetPWSecureAPIResult[JSONType](String API, Boolean ForceReLogin)
```
and

```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)
```
and
```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetUnsecured(String URI)
```

**Comment by BJReplay** [comment]
OK, I finally got upgraded this morning to 1.20.0, and (luckily) I'm off sick.  I can confirm - with no code changes - that you can get logging working on 1.20.0:

1. Make sure you have a "static" IP assigned (either in your router DHCP) or otherwise.  If your router provides DNS services that resolve DHCP host names to IPs, then make sure the host name is set to powerwall and you can skip step 2
1. Add an entry in windows\system32\drivers\etc\hosts that resolves powerwall to your static IP
1. Browse to https://powerwall, and click through the certificate warnings until you can display the powerwall GUI.
1. Save the certificate to your local drive (or the server where powerwallservice is running)
1. Install the certificate to the LocalMachine (not current user) into the Trusted Root Certificates Store
1. Close the browser, and re-open to https://powerwall, and confirm there is no certificate error.
1. Update the IP address of the powerwall gateway in the powerwallservice.exe.config to https://powerwall, and restart the service.

It should now correctly log from the powerwall on https.  Now that I have a test environment, I will see if I can get control working again.

**Comment by AnthonyBe** [comment]
Welcome to 1.20.0 :)

A few questions:

1. So you're saying that it can't be done using IP addresses and that you HAVE to create the host mapping for powerwall and use that hostname for this all to work? Just want to confirm this.
2. In your step 5 where you say "Trusted Root Certificates Store" do you mean "Trusted Root Certification Authorities certificate store"? I do not have a certificate store called just "Trusted Root" (running Windows 10)

**Comment by BJReplay** [comment]
1 - that is the way to work around the need to not check the certificate - using the host name then means that the certificate is considered valid - it has the following SANs
DNS Name=teg
DNS Name=powerwall
DNS Name=powerpack
IP Address=192.168.90.1
IP Address=192.168.90.2
IP Address=192.168.91.1

2 - yes (sorry, didn't check, just wrote from memory), just confirmed it is Trusted Root Certification Authorities

**Comment by BJReplay** [comment]
1 - yes.  I can force the code to ignore the certificate (and, now that I have firmware 1.20.0 to test against, should do this, but haven't yet), but you don't need to ignore the certificate if you install it and access the gateway via a host name.

**Comment by AnthonyBe** [comment]
OK, done it as per above but I'm still getting the same errors.

I can confirm that I can browse http://powerwall and get the PW web UI with no browser errors.
I can confirm that I've updated the IP address of the powerwall gateway in the powerwallservice.exe.config to https://powerwall

In the Event Log, after the service successfully starts I get 4 errors followed by a warning:


```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)

```
```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetPWSecureAPIResult[JSONType](String API, Boolean ForceReLogin)
```

```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)

```
```
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetUnsecured(String URI)

```

Warning is event ID 513

`Failed to obtain current operation mode`

**Comment by BJReplay** [comment]
OK, those errors indicate it is trying to log into the powerwall (not just read the logs).  The new build I've just uploaded to https://github.com/BJReplay/PowerwallService/blob/master/PowerwallServiceBeta1.5.0.0.zip has the fixed login code.  Change your username in the .config file to installer (from user@email.com).

Though that error is different to what I've seen (I just got 403s until I fixed the login call), and may be related to something else I saw that said that you needed to allow for TLS 1.2 mentioned at https://github.com/vloschiavo/powerwall2/issues/9#issuecomment-405102800

**Comment by AnthonyBe** [comment]
Just testing now.. and trying to sort through certificate weirdness..
I just browsed https://powerwall and got a cert error (despite this not occurring a few hours ago). Compared the cert in the browser to the one I had downloaded and installed only a few hours ago and the serial number had changed, public key had changed from RSA (2048 bits) to ECC (256 bits).. weird..

Anyway, have downloaded and installed the new certificate and confirmed that I can browse https://powerwall with no certificate errors.

Updated the powerwallservice.exe from 1.4.3.2 to 1.5.0.0

Changed the PWGatewayUsername from user@email.com to installer.


Am not getting any errors in the Event Log.. but also getting no event entries at all after "Service started successfully.". I'm not convinced this is working.

If I look at my Power BI dashboard, it stays empty :(
If I check my SQL DB sitting in Azure, I can see new records going in. In fact, it seems new records were going in earlier when all those errors were being thrown?!!?

**Comment by AnthonyBe** [comment]
Oh wait.. my mistake.. entries are no longer flowing into the DB so that confirms my theory that nothing is working now, and also not generating any errors.

It seems the last entries written into the DB were earlier this afternoon (when I WAS getting errors in Event Log)!

**Comment by AnthonyBe** [comment]
I've reverted to v1.4.3.2 of the service executable, and while I'm getting the errors again in the Event Log, I am getting new records being written into the SQL DB and the Power BI dashboard is populated again.

**Comment by BJReplay** [comment]
OK, I need to swap branches and re-apply those changes to an older branch.  The build had some other refactoring in it; it's working for me, but not sure why not for you.  Thanks for testing.  At least we know that the fix works.  Interesting that the certificate had changed!

**Comment by AnthonyBe** [comment]
Looks like it could be a moot point now that Tesla are disabling people's access to the web UI and API after upgrading them to 1.20.0 :(

**Comment by AmateurCritic** [comment]
I'm using Tesla Powerwall Gateway, with firmware version 1.20.0 and have a raspberry pi running stretch, to pull the State of Charge, (soe) and write it to a file.

$ wget -q -O soe --no-check-certificate https://192.168.0.6/api/system_status/soe
Quiet operation, ignore certificate and (re)write to file "soe"

$ cat soe
{"percentage":39.1497885599822}

**Comment by BJReplay** [comment]
https://drive.google.com/open?id=1jToF9YgUMXvWyTc-KDyokYHTd9wdnMLX

This build might fix @AnthonyBe and CL's problem.  Should work on 1.22.  Not tested, but based on code I'm running against 1.22, which I managed not to make to the master branch last time I tried.

**Comment by AnthonyBe** [comment]
Cheers Bernard!

I had the hard drive fail at the start of the week in the PC that I was running all of this on so I'm in the process of setting it all up again from scratch. Should be able to finish it off sometime over the weekend, or early next week, so I'll let you know how I go.

**Comment by BJReplay** [comment]
Another build - ensure that calls to sitemaster/run (called after all operations that set mode) use bearer token to avoid 403.  See https://github.com/BJReplay/PowerwallService/blob/master/PowerwallServiceBeta1.7.1.0.zip for new version

**Comment by AnthonyBe** [comment]
Cheers. I was seeing a spate of errors in my initial testing with 1.7.0.0 on the weekend but was seeing same as I rolled back through 1.5.0.0 and 1.4.3.2 so I'll now test with 1.7.1.0 and see what happens!

**Comment by gibbo9000** [comment]
Hi Guys.  Awesome bit of work!  I am new to this and seem to be getting a mix of (duplicated) 401 and 403 errors from the service trying to log in.  Powerwall is running 1.21.0 and I am using 1.7.1.0.  Pretty sure I have the config file correct and it is collecting Solcast data - just not talking to Powerwall.  I note this is the first time I have tried this so haven't talked to PW this way before.  Using 'installer' and Gateway serial with an 'S' infront (STG118 . . . etc).  https://powerwall is clear of certificate errors.  Anything else obvious to check?
![pw1](https://user-images.githubusercontent.com/14179845/45679590-48694f00-bb7c-11e8-8149-c28c2affc318.JPG)
![pw2](https://user-images.githubusercontent.com/14179845/45679596-4d2e0300-bb7c-11e8-8a31-6ef6fe9a24a6.JPG)
![pw3](https://user-images.githubusercontent.com/14179845/45679601-5028f380-bb7c-11e8-8498-a22323d01615.JPG)
![pw4](https://user-images.githubusercontent.com/14179845/45679609-528b4d80-bb7c-11e8-9117-390fc84fda5e.JPG)

**Comment by BJReplay** [comment]
I think you will need to log into the powerwall web GUI, and set the installer password for the first time (so that it is NOT the default of gateway serial number) - I think this was introduced with 1.20 or 1.21.  

If you log into the gateway with the default password, you should change it (possibly you only do this by stepping through the wizard).

I can't test whether or not the powerwall service can log in using the default password of the gateway anymore (at least without forcing a password reset on my gateway) because I ran through the wizard and got to the bit that changed the password before I then got the code working with the new login model.

**Comment by gibbo9000** [comment]
Thanks BJ.  Looks like for a new install of PW2 with 1.21.0 the installer changes the installer PW from the standard STG... to an auto generated 8 digit one.  I think I saw it in his notes but he didn't give it to me.  Fortunately there is a reset process without need to run the full wizard process (prompted from Web GUI - toggle on/off switch, enter Gateway no, and off you go).  Just have a small config issue to fix when I get a few minutes.

**Comment by AnthonyBe** [comment]
Ah.. that would explain it. I was seeing all of those 401 and 403 errors as well but just hadn't had a chance to go back and check everything.

So, I've gone and logged in and reset the installer password.
I've plugged this new password into the PWGatewayPassword setting.

I'm still getting the same errors:

```
The remote server returned an error: (400) Bad Request.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetSolCastResult[JSONType]()
```

```
Object reference not set to an instance of an object.

   at PowerwallService.PowerwallService.GetForecasts()
```
```
The remote server returned an error: (401) Unauthorized.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)
```
```
The remote server returned an error: (403) Forbidden.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetPWSecureAPIResult[JSONType](String API, Boolean ForceReLogin)
```
then 2 of these:
```
The remote server returned an error: (401) Unauthorized.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.LoginPWLocal(Boolean ForceReLogin)
```

`Failed to obtain current operation mode`

**Comment by AnthonyBe** [comment]
OK, problem seems to be on the Tesla side. When I reset the Installer login in the WebUI, the new password it gives me doesn't seem to work on subseqent logins? I've gone through the process 4 times now and same result every time.

**Comment by BJReplay** [comment]
@AnthonyBe I think I recalled a similar experience.  I can't remember how I ended up working around it.  Away from home at the moment, so can't check.  Will try to have a look on the weekend.

**Comment by AnthonyBe** [comment]
OK, had more time to play with this.. the new installer password works, but I have to check the checkbox beside "Force Launch Wizard" which is on the login box and is shown when you click the "click for more" just after "If the Wizard does not launch"

Does your service cater for this?

Hmmm... so where does that leave us? Especially in my case where I just want it for logging only?


In case it is relevant, my PW is on 1.22.1

**Comment by BJReplay** [comment]
@AnthonyBe try setting the PWGatewayUsername parameter to installer - the code still pulls this from the config file.  The logic was that I could support earlier versions (required an email) and later versions (requires installer), though I haven't coded for version dependent handling of mode vs real_mode in the operation call.

**Comment by AnthonyBe** [comment]
Got it- I'll give it a crack and report back.

**Comment by AnthonyBe** [comment]
Setting **PWGatewayUsername** parameter to _installer_ did the trick!
