### ISSUE TITLE
FYI: Solcast API - Free/beta period ending soon

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#27]
I'm sure you've also got the email from Solcast :)

I guess the good news is that they seem to not want to charge everybody for everything based on these comments in the email:

`In reflection of our company mission to make solar data and forecasting easily accessible and affordable, Version 1.0 of the API services will have a free trial for most products.`

and 

`Lastly, if you are a student, non-commercial researcher, or with a non-profit entity - we have plans to provide you with free ongoing access to certain products in Version 1.0, including many of the new features. We support your work and your mission. Contact us, we would love to speak to you about your project and how our new capabilities could help you.`

BJ - I think you are a "non-commercial researcher" aren't you? :)

**Comment by BJReplay** [comment]
I reckon I might be - but I think I owe them data too - I have been in touch.  I'll try to meet with the guys, because for that exclusion to work, I need to integrate an ongoing API key into PWS and remove that from config.

**Comment by AnthonyBe** [comment]
I'm now seeing the following errors:

```
The remote server returned an error: (400) Bad Request.

   at System.Net.HttpWebRequest.GetResponse()
   at PowerwallService.PowerwallService.GetSolCastResult[JSONType]()
```
```
Object reference not set to an instance of an object.

   at PowerwallService.PowerwallService.GetForecasts()
```
when I get the API URL and manually populate my values into it, I get the following on the webpage produced:

```
Response_status
Error_code               GreaterThan
Message                  'Capacity' must be greater than '0'.
```

which is weird because my capacity is set to 6930. I've messed around with different values, tried wrapping the value in ' ' , tried removing the value entirely, but same response every time.

Here is my populated URL (API key removed):

https://api.solcast.com.au/pv_power/forecasts?longitude=149.117&amp;latitude=-35.277&amp;capacity=6930&amp;tilt=40&amp;azimuth=315&amp;install_date=20171013&amp;api_key=<API_key_removed>&amp;format=json

**Comment by BJReplay** [comment]
See https://solcast.com.au/api/pv-power-requests.html:

"The angle (degrees) from true north that the PV system is facing, if tilted. Must be between -180 and 180. An azimuth of 0 means the system is facing true north. Positive values are anticlockwise, so azimuth=-90 for an east-facing system, and azimuth=135 for a southwest-facing system. Default value is 0 (north-facing) in the southern hemisphere, 180 (south-facing) in the northern hemisphere."

azimuth = 315 should be 45, I believe.  If I sub in my key and put in 45, it works, but if I put in 315, it gives me an error - albeit that the azimuth isn't correct.  Worth double checking your config entries.  

Also worth checking installdate - should be yyyy-MM-DD I believe - that may be tripping it up as well.

Mine are (excluding key) FYI

            <setting name="SolcastAddress" serializeAs="String">
                
                <value>https://api.solcast.com.au/pv_power/forecasts?longitude={0}&amp;latitude={1}&amp;capacity={2}&amp;tilt={3}&amp;azimuth={4}&amp;install_date={5:yyyyMMdd}&amp;api_key={6}&amp;format=json</value>
            </setting>
            <setting name="SolcastAPIKey" serializeAs="String">
                
                <value> API Key Removed </value>
            </setting>
            <setting name="PVSystemLongitude" serializeAs="String">
                
                <value>144.9</value>
            </setting>
            <setting name="PVSystemLattitude" serializeAs="String">
                
                <value>-37.8</value>
            </setting>
            <setting name="PVSystemCapacity" serializeAs="String">
                
                <value>4850</value>
            </setting>
            <setting name="PVSystemTilt" serializeAs="String">
                
                <value>5</value>
            </setting>
            <setting name="PVSystemAzimuth" serializeAs="String">
                
                <value>-123</value>
            </setting>
            <setting name="PVSystemInstallDate" serializeAs="String">
                
                <value>2012-04-19</value>
            </setting>

**Comment by AnthonyBe** [comment]
Ah, OK. The comment in the PowerService.exe.config states:

`Put your PV system azimuth here (what compass direction does it face? 0 for north, 90 for east, 270 for west, and so on`

..so that might need to be changed to:

`Put your PV system azimuth here (what compass direction does it face? 0 for north, -90 for east, 90 for west, and so on`


Changed my Azimuth setting from 315 to 45 and the errors are gone and it is now correctly logging SolCast Three Day Forecast return data!

**Comment by BJReplay** [comment]
Yeah, that was my advice in the original config file (and I was wrong).  I need to update the doco, and check if the sample config still has the wrong instructions.

**Comment by Layoric** [comment]
Hi @BJReplay , an FYI update here (I currently work for Solcast) we will be transitioning beta users to our 'freemium' offering within the next 30 days. This will include daily API call limits to 20 a day for those that sign up to our service as "hobbyists". This will mean we will be keeping this service free long term for those users to integrate with the PowerwallService tool. Users can see what account type they are signed up as via our [API Toolkit account page](https://toolkit.solcast.com.au/account). Users can reach out to us via the API Toolkit if they are a hobbyist but their account type is showing something else to get the higher free daily API calls.

Currently it looks like PowerwallService might be updating forecasts every 10 minutes which will hit the daily limit and maybe stop working. I think ideally the tool would only forecast during local day time every 1 hour, this should keep things going without hitting the daily limit.

**Comment by BJReplay** [comment]
@Layoric Hi Darren, thanks for the reminder.  I need to get onto this, after I get over the flu.  I'm going to hit the forecast every half hour from around 11pm; this should give me the best data for pre-charging from when you need to start (if your powerwall will only charge at 1.7kW) to when you need to top up just before peak starts (when cloud has rolled in overnight and is spotted by the solcast magic).

**Comment by Layoric** [comment]
@BJReplay that sucks you caught the flu this winter.

You should get best performance by leaving forecasts to as late as you can for whatever strategy of battery charging you want. The satellite data updated every 10 minutes only looks forward ~4 hours before results start reflecting longer term forecasts based on numeric weather models + our machine learning with historic satellite imagery. 

Forecasts at 11pm local looking towards sunrise most likely won't change much until sunrise-4 hours so you can safely space them further a part to save some daily calls during the day or when the time horizon you are interested in is shorter and the latest data is more important.

Hope that helps (and you're feeling better soon)!

**Comment by BJReplay** [comment]
Thanks, that is useful advice.

**Comment by BJReplay** [comment]
[PowerwallService2.0.0.0.zip](https://github.com/BJReplay/PowerwallService/files/3438774/PowerwallService2.0.0.0.zip)

Just updated to grab forecasts hourly until sunset (from midnight).
