### ISSUE TITLE
PW v1.21.0 firmware appears to have seperated out Customer login

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#28]
Just thought I'd note this development in the Tesla PW firmware as it may (have) to play a part in future development. It may also be a better way of separating out *how* you interact with the PW in code depending on whether the user has it in "Logging only" mode (like myself) or in "Control mode" like yourself :)

v1.21 release notes (https://www.tesla.com/support/energy/own/powerwall/software-updates):

```
Added Customer login to Gateway to allow:

- Local monitoring of power flow and charge level
- Viewing system information
- Updating network settings
- Learn More

```

That last bullet point is an odd one.. "Learn More".. but no hyperlink to anywhere.. wonder what it means?

**Comment by BJReplay** [comment]
At this stage, all standard (state of charge, power flows) logging works on 1.21.0 without logging in.  Installer login continues to work for control (but requires changes to login and mode setting as JSON body payload has changed for both).

Customer login allows you to configure network (and allows WiFi, LAN and Cellular to all be configured at the same time), change the customer password, and display a status summary:

GATEWAY nnnnnnn-01-F--T17Hnnnnnnn
SITE NAME BJReplay's Powerwall
BACKUP CAPABILITY Backup Capable
MODE Self Consumption
BACKUP RESERVE 55%
GRID CODE 50Hz_230V_1_ASNZS4777.2:2015_AU
TIME ZONE Australia/Melbourne
CUSTOMER VERSION 1.21.0 
NETWORK Wi-Fi, ETHERNET, CELLULAR
POWERWALL 1 PartNumber: 1092170-03-G Serial: TGnnnnnnnnnnTN
SUMMARY COMPILATION TIME 2018-8-11 12:20:42 (UTC+10)

**Comment by AnthonyBe** [comment]
Interestingly, my system upgraded from v1.20.0 to v1.21.0 yesterday. PowerBI service still all running nicely.

**Comment by BJReplay** [comment]
Closing - will address any issues identified.
