### ISSUE TITLE
Firmware v1.22.1

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#29]
Hey guys,

Has firmware 1.22.1 hit your units yet? Since it went on mine I get loads of fan noise after setting a new backup reserve percentage. It's really loud!

Just wondering if I have an issue, or if this is a new 'feature'

Cheers

**Comment by BJReplay** [comment]
I'm running 1.22.1 and have been for about a week.  I'll have to check re fan noise after setting reserve - but I've been struggling with mechanical vibration which is even more noise - acoustically coupled through the wall mount and into our bedroom.  Tesla finally sending someone on site after about six weeks on Monday.

**Comment by spoonwzd** [comment]
Thanks. Would be interested to hear if yours does the same. I did call Tesla but their support appears to suck. I have a loud fan noise Tesla. I don't need to send you a video of the noise.

I've paid a bit more notice to the behaviour. After every change to configuration the fans run for about 30 mins or so, getting briefly louder at the end of the period before going quiet. It doesn't seem related to charging, discharging or temperature - it's just what happens after you sitemaster/run.

As the backup reserve % gets changed frequently overnight when precharging to cater for PV shortfall, it means the fan runs as high RPM all night!

At the end of the overnight period where it returns to a normal state and the configuration doesn't change it stay's silent all day, even when under heavy charges or discharges.

Would be good to know if yours does the same.

Cheers

**Comment by BJReplay** [comment]
Hey @spoonwzd, I can confirm, fan runs flat out for that same 30 minutes or so after setting reserve percentage - powerwall was in standby at the time (reserve percentage set to current SOC so that the battery stopped supplying the house load and instead it came from off peak grid).  Waiting now for 1.22.2 to see if it fixes it.

**Comment by spoonwzd** [comment]
Thanks for the confirmation both here and on the Tesla forums :) Let's hope they fix it.
