### ISSUE TITLE
Typo in Event ID 106 (Service Stopping)

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#31]
Very minor (I'd fix it myself except it's more effort to fork, edit, pull, etc.).

The event ID 106 generated when stopping the service has a typo in the service details:

`Powerwall Service Stoping`

should be

`Powerwall Service Stopping`

**Comment by BJReplay** [comment]
Thanks.  I'd noticed this in the event log, but never while working on the code.
