### ISSUE TITLE
"running" event (Source=PowerwallService, EventID = 200) every minute - is it necessary?

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#4]
I know these sorts of things are handy during alpha/beta testing but given the amount of events logged, I'm wondering if having this event logging every minute is necessary? or can at least be optionally disabled to prevent quite as much Event Log spam? :)

**Comment by BJReplay** [comment]
Will consider a logging level parameter.  I do see your point - and much of the logging (for me, at least) is now redundant given I have it pushing charging monitoring / intent to a PowerBI streaming dashboard :)

**Comment by BJReplay** [comment]
See build 0.9.9.0 - release notes in zip
https://github.com/BJReplay/PowerwallService/blob/master/PowerwallServiceAlpha0.9.9.0.zip
