### ISSUE TITLE
How do you upgrade when new version released?

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#5]
To date, my method has been:
1. Stop PowerwallService
2. From downloaded zip file, copy over all files into existing folder EXCEPT PowerwallService.exe.config
3. Check PowerwallService.exe.config for new parameters and merge into my personalised version (alternatively, make backup of the personalised config file, copy new one across and re-enter all parameters as required)
4. Start PowerwallService
5. Check Event Log for errors

Not sure if you'd like to document this somewhere (after vetting, updating, etc.)?

**Comment by BJReplay** [comment]
Good Point - needs doco.  A release really is only the main exe, the Newtonsoft DLL, and the config changes.

**Comment by BJReplay** [comment]
I will include release notes in releases, and update general doco at a later date.
