### ISSUE TITLE
Catering for heavier consumption at weekends

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#7]
I've been reviewing my system history and have identified that power consumption in the home can be 20-40% more at weekends.

Can we cater for this behavior in a future PwS release by pre-charging more on these days?

**Comment by BJReplay** [comment]
If you're logging to a database, this is on my roadmap - setting targets using historical consumption history (by day of week).  I'm going to also consider adding HDD and CDD (heating and cooling degree days) to allow for load flex for running heating or cooling - that will have to start of fairly crudely, though I'm thinking of uploading my half-hourly meter data to back fill my history.

That said, apart from my grand plans, it would be easy enough to add a weekend power consumption figure as well - though my plan is to predict by day of week (my wife works 3 days a week), so our consumption patterns vary by day.

**Comment by spoonwzd** [comment]
I plan to set up the database at some point, but I'm already sending my Powerwall output to pvoutput.orv using their scripts and if I change things now I risk messing up my history. I think.

I envisaged a PWPeakConsumptionWeekend variable as an easy short-term fix.

For your Wife's working days, perhaps a variable for each day is an option? PWPeakConsumptionMonday, PWPeakConsumptionTuesday, etc.

**Comment by BJReplay** [comment]
Added PWPeakConsumptionWeekend to release 1.0
